### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by robinwiel** [VU-Programming/AP2-Skeleton#1]
### Details

VUNet ID : rwl440
Assistant: George Karlos
### Issue

Our program is failing the final test every time. I have tried using -v and -e to get more details on the error, but I do not understand where our program is failing. Is there a way to see what the input is?

The "INPUT ERROR: Character mismatch, was expecting: "}" is our exception message when the parser is reading a set, cannot find anymore numbers to read, and therefore calls the character method to read the "}".
### Output

[   INFO] Running command `java -jar build/libs/AP2-1.0.jar`
[SUCCESS] Set match!
[SUCCESS] Set match!
[SUCCESS] Set match!
[   FAIL] Expected `INPUT ERROR: Character mismatch, was expecting: "}"` to be a set!

**Comment by BlackNovaTech** [comment]
Since there is no other output, i will assume that the test suite is calc.
It passed 3 assertions, thus it correctly printed out behaviour three times, and the failing lines were line 10-11 from calc.in, namely:

```
Dirk = { 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42 }
? Dirk
```

Anyhow, on to the question of if I can show what input belongs where, it is a tricky one.
What happens is that we feed the entire input to the program (the `io/<test>.in`) and compare every line from the output of the program to the output (`io/<test>.out`).
In calc, finding the corresponding input is quite easy, as every print statement is one line of the output.
In syntax however, we also try erroneous input, thus figuring out what input caused what becomes quite a bit harder.

Anyhow, I might improve the testing a bit later, but for now this is a complete port of the tests as ran by PracTool (but then in python), and since I'm using mostly the same files as PracTool, I'm mostly bound by the same limitations.
